Add rule to find missing intrinsic specifiers in `use` statements
PlasmaFAIR/fortitude pull request #253
Opened 2024-12-22 21:49 UTC by imciner2

This adds a linting rule that checks `use` statements for if they refer to an intrinsic module defined in the standard, and if so that the `use` statement includes the `intrinsic` modifier (or alternately, the `non_intrinsic` modifier if someone really wants to override a compiler intrinsic module). Including it is good practice since the compiler will prioritize modules outside the compiler first, so this makes the need for the compiler version explicit.

2025-01-03 18:22 UTC, LiamPattinson requested changes
Amazing, many thanks for the contribution! :heart:

Overall this is looking great, but a few small changes will be needed before we can merge:

- The fix doesn't work in cases where a `::` separator isn't present, such as `use iso_fortran_env`. As a `::` is optional for a plain `use` statement but necessary after adding `intrinsic`, we need to add it if it's missing. I've added a suggestion below that I think fixes the issue, and we'll need to add a plain `use` statement to the tests too.
- The fix has the potential to break a user's code if they're deliberately using their own module named `iso_fortran_env` (or one of the other intrinsic modules) for whatever reason, so unfortunately it'll have to be listed as an unsafe fix.
- We're following [Ruff's rule naming convention](https://docs.astral.sh/ruff/contributing/#rule-naming-convention), so I think a better name for it would be `MissingIntrinsic`, as that would mean users could ignore this rule by adding the comment `! allow(missing-intrinsic)`. With that said, I'm only just now realising that the rule `UseAll` in the same file would be better named `MissingOnly`, but as that would be a breaking change I'll leave it for another PR.

2025-01-06 17:50 UTC, imciner2 commented on fortitude/src/rules/modules/use_statements.rs
> +            return some_vec![Diagnostic::from_node(UseIntrinsic {}, node).with_fix(fix)];
Thanks, this appears to be working. I was thinking it might be better to search all children nodes for the `::`, but I guess since the standard only allows the module nature or the `::` before the module name, that it is probably safe to assume the first node would be `::`.

2025-01-07 09:22 UTC, LiamPattinson requested changes
All looks good, except that it needs to be marked an unsafe edit. I'd recommend making the change locally rather than directly committing the suggestion below, as the test snapshots will need to be updated too.

2025-01-07 09:22 UTC, LiamPattinson commented on fortitude/src/rules/modules/use_statements.rs
> +            let fix = Fix::safe_edit(Edit::insertion(intrinsic.to_string(), start_pos));
```suggestion
            let fix = Fix::unsafe_edit(Edit::insertion(intrinsic.to_string(), start_pos));
```

2025-01-07 11:36 UTC, LiamPattinson approved these changes
All looks good to me! Thanks again for the contribution, I really appreciate it. @ZedThree I'm happy to merge this if you are.

2025-01-07 11:42 UTC, ZedThree approved these changes
Looks great! Thanks for the contribution @imciner2, we really appreciate it!

2025-01-07 11:42 UTC, merged